### ISSUE TITLE
TopProver は現在でもメンテされていますか？

### ISSUE THREAD

**Issue by Seasawher** [asi1024/topprover-lean-example#1]
はじめまして．https://top-prover.top/ を拝見して，とても素敵な試みだと思いました．私は Coq には詳しくありませんが，定理証明支援系である Lean に興味があり，Lean でコンテストを開催することにも興味があります．（Lean は２週間前にバージョン4が正式にリリースされたばかりです）

そこで Lean4 に対応しませんかという issue を開くつもりだったのですが，最近 TopProver のサイトの更新がないようですので，現在のメンテ状況や，新しいメンテナを募集しているかどうかなどをお尋ねしたいと思いました．

ここに issue を開くのが不適切であったら申し訳ありません．

**Comment by asi1024** [comment]
@Seasawher ご連絡ありがとうございます。現状、過去の問題を解けるように公開しているだけで、大したメンテナンスは行っておりません。Lean4 をサポートすること自体はすぐにできると思いますし、コンテストを開催することはできますが、今はコンテストを開いて参加者が自然と集まる状態ではないと思っています 😿

**Comment by Seasawher** [comment]
お返事ありがとうございます

> Lean4 をサポートすること自体はすぐにできると思いますし、コンテストを開催することはできますが、

私はlean4でコンテストを開催することに興味がありますが、（私の技術力不足により）方法がわからないので困っています。どのようにすればコンテストシステムを実装できますか？差し支えなければ教えていただきたいです。

**Comment by asi1024** [comment]
"オンラインジャッジシステム 作り方" で検索したら参考になる記事がいろいろ見つかります。

ただ、メンテナンスはそれなりに大変ですし、重めのソルバーを使うTacticを動かそうとするとそれなりに性能の良いサーバーを借りる必要がありお金もかかるので、コンテストシステムを作ることに拘らないのであれば、Discord とかでコミュニティを作って手動で開催する方がずっと手軽だと思います。

コンテストが完成したら是非招待してください :smiley:
